spotify_artists.settings:
  type: config_object
  label: 'Spotify Artists settings'
  mapping:
    spotify_client_id:
      type: string
      label: 'Spotify Client ID'
    spotify_client_secret:
      type: string
      label: 'Spotify Client Secret'
    artist_ids:
      type: sequence
      label: 'Artist IDs'
      sequence:
        type: string
        label: 'Artist ID'